# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AtWork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AtWork
  pod 'MapboxGeocoder.swift', '~> 0.10'
  pod 'MapboxNavigation', '~> 0.22'

end
